services:
  - type: web
    name: coughsense-api
    runtime: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
    - key: PYTHON_VERSION
      value: "3.10.6"
    - key: TF_CPP_MIN_LOG_LEVEL
      value: "3"
    - key: TF_ENABLE_ONEDNN_OPTS
      value: "0"
